create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    title text not null,
    images text[] not null default '{}',
    created_at timestamptz not null default now()
);

create table if not exists public.members (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.members enable row level security;

drop policy if exists "Public can read projects" on public.projects;
drop policy if exists "Public can read members" on public.members;
drop policy if exists "Authenticated users manage projects" on public.projects;
drop policy if exists "Authenticated users manage members" on public.members;

create policy "Public can read projects" on public.projects for select using (true);
create policy "Public can read members" on public.members for select using (true);
create policy "Authenticated users manage projects" on public.projects for all to authenticated using (true) with check (true);
create policy "Authenticated users manage members" on public.members for all to authenticated using (true) with check (true);
