create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    title text not null,
    images text[] not null default '{}',
    location text not null default '',
    description text not null default '',
    project_date date,
    created_at timestamptz not null default now()
);

alter table public.projects add column if not exists location text not null default '';
alter table public.projects add column if not exists description text not null default '';
alter table public.projects add column if not exists project_date date;

create table if not exists public.members (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    profession text not null default '',
    description text not null default '',
    photo text not null default '',
    created_at timestamptz not null default now()
);

alter table public.members add column if not exists description text not null default '';
alter table public.members add column if not exists photo text not null default '';
alter table public.members add column if not exists profession text not null default '';

create table if not exists public.social_links (
    id bigint generated by default as identity primary key,
    platform text not null unique,
    url text not null default '',
    updated_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.members enable row level security;
alter table public.social_links enable row level security;

drop policy if exists "Public can read projects" on public.projects;
drop policy if exists "Public can read members" on public.members;
drop policy if exists "Authenticated users manage projects" on public.projects;
drop policy if exists "Authenticated users manage members" on public.members;
drop policy if exists "Public can read social links" on public.social_links;
drop policy if exists "Authenticated users manage social links" on public.social_links;

create policy "Public can read projects" on public.projects for select using (true);
create policy "Public can read members" on public.members for select using (true);
create policy "Authenticated users manage projects" on public.projects for all to authenticated using (true) with check (true);
create policy "Authenticated users manage members" on public.members for all to authenticated using (true) with check (true);
create policy "Public can read social links" on public.social_links for select using (true);
create policy "Authenticated users manage social links" on public.social_links for all to authenticated using (true) with check (true);
