create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    title text not null,
    images text[] not null default '{}',
    location text not null default '',
    description text not null default '',
    project_date date,
    is_example boolean not null default false,
    created_at timestamptz not null default now()
);

alter table public.projects add column if not exists location text not null default '';
alter table public.projects add column if not exists description text not null default '';
alter table public.projects add column if not exists project_date date;
alter table public.projects add column if not exists is_example boolean not null default false;

insert into public.projects (title, images, location, description, project_date, is_example)
select 'Residencia Horizon', array[
    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',
    'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85'
], 'Ciudad de México', 'Residencia de escala doméstica que integra luz natural y materiales honestos.', '2026-01-01', true
where not exists (select 1 from public.projects where title = 'Residencia Horizon' and is_example = true);

insert into public.projects (title, images, location, description, project_date, is_example)
select 'Pabellón Monolito', array[
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85'
], 'Monterrey, México', 'Un espacio de encuentro definido por la masa, la sombra y la continuidad material.', '2025-08-01', true
where not exists (select 1 from public.projects where title = 'Pabellón Monolito' and is_example = true);

insert into public.projects (title, images, location, description, project_date, is_example)
select 'Torre Eje', array[
    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85',
    'https://images.unsplash.com/photo-1600566753051-9c1c8b5f5d1c?auto=format&fit=crop&w=1200&q=85'
], 'Guadalajara, México', 'Una exploración vertical de proporción, estructura y relación con el paisaje urbano.', '2024-03-01', true
where not exists (select 1 from public.projects where title = 'Torre Eje' and is_example = true);

create table if not exists public.members (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    profession text not null default '',
    description text not null default '',
    photo text not null default '',
    instagram text not null default '',
    created_at timestamptz not null default now()
);

alter table public.members add column if not exists description text not null default '';
alter table public.members add column if not exists photo text not null default '';
alter table public.members add column if not exists profession text not null default '';
alter table public.members add column if not exists instagram text not null default '';

create table if not exists public.social_links (
    id bigint generated by default as identity primary key,
    platform text not null unique,
    url text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.site_content (
    id bigint generated by default as identity primary key,
    content_key text not null unique,
    content_value text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.services (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null default '',
    created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.members enable row level security;
alter table public.social_links enable row level security;
alter table public.site_content enable row level security;
alter table public.services enable row level security;

drop policy if exists "Public can read projects" on public.projects;
drop policy if exists "Public can read members" on public.members;
drop policy if exists "Authenticated users manage projects" on public.projects;
drop policy if exists "Authenticated users manage members" on public.members;
drop policy if exists "Public can read social links" on public.social_links;
drop policy if exists "Authenticated users manage social links" on public.social_links;
drop policy if exists "Public can read site content" on public.site_content;
drop policy if exists "Authenticated users manage site content" on public.site_content;
drop policy if exists "Public can read services" on public.services;
drop policy if exists "Authenticated users manage services" on public.services;

create policy "Public can read projects" on public.projects for select using (true);
create policy "Public can read members" on public.members for select using (true);
create policy "Authenticated users manage projects" on public.projects for all to authenticated using (true) with check (true);
create policy "Authenticated users manage members" on public.members for all to authenticated using (true) with check (true);
create policy "Public can read social links" on public.social_links for select using (true);
create policy "Authenticated users manage social links" on public.social_links for all to authenticated using (true) with check (true);
create policy "Public can read site content" on public.site_content for select using (true);
create policy "Authenticated users manage site content" on public.site_content for all to authenticated using (true) with check (true);
create policy "Public can read services" on public.services for select using (true);
create policy "Authenticated users manage services" on public.services for all to authenticated using (true) with check (true);
